---
- name: install and configure mariadb
  hosts: test
  remote_user: root
  become: yes

  vars:
    mysql_port: 3306

  tasks:
  - name: install mariadb
    yum: name=mariadb-server state=present

  - name: create mysql configuration file
    template: crc=my.cnf.j2 dest=/etc/my.cnf
    notify: restart mariadb

  - name: create mariadb log file
    file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

  - name: start mariadb service
    service: name=mariadb state=started enabled=yes

  handlers:
  - name: restart mariadb
    service: name=mariadb state=restarted
