---
- name: install and configure mariadb
  hosts: test
  remote_user: root
  become: yes

  vars:
    mysql_port: 3306

  tasks:
  - name: install packages
    yum: name={{item}} state=present
    with_items:
    - mariadb-server
    - MySQL-python
    - libselinux-python

  - name: looping over environmental facts
    debug: msg={{item.key}}={{item.value}}
    with_dict: ansible_env
